<a href="https://colab.research.google.com/github/anitasari15/StatistikaGroup2/blob/master/Implementasi_Random_Sampling_Menggunakan_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Implementasi Random Sampling Menggunakan Python 
## 1. Random Sampling Pada List 
Berikut contoh bagaimana cara untuk mengimplementasikan random sampling pada list (array) menggunakan python
### 1.1 Tanpa Redudansi 
Untuk menerapkan random sampling tanpa terjadinya redudansi data, maka kita dapat menggunakan fungsi *random.sample()* <br>
contoh random sampling volume kendaraan pada senin - jumat pada kawasan taman pintar 


In [1]:
import random

data = [4112, 3913, 3572, 4803, 3809] 
print("3 data terpilih untuk dijadikan sampel adalah : ", random.sample(data, k=3))



3 data terpilih untuk dijadikan sampel adalah :  [4112, 3913, 4803]


### 1.2 Dengan Redudansi 
Untuk menerapkan random sampling dengan menyertakan redudansi data, maka kita dapat menggunakan fungsi* random.choices()* <br>
contoh random sampling volume kendaraan pada senin - jumat pada kawasan taman pintar


In [2]:
import random

data = [4112, 3913, 3572, 4803, 3809]
print("3 data terpilih untuk dijadikan sampel adalah : ", random.choices(data, k=3))



3 data terpilih untuk dijadikan sampel adalah :  [4803, 4112, 4803]


### 1.3 Nested List 
Untuk menerapkan random sampling pada nested list, kita perlu menggunakan library numpy, pertama untuk membuat nested list dapat menggunakan fungsi *numpy.array()*, kemudian untuk memilih sampel secara acak dari nested list tersebut dapat menggunakan fungsi *numpy.random.randint(*) <br>
contoh random sampling volume kendaraan pada senin - jumat (pagi, siang, sore) pada kawasan taman pintar

In [3]:
import random
import numpy

data = numpy.array([
    [4112, 3975, 5412],
    [3913,5123, 4132],
    [3572, 4129, 3251],
    [4083, 4142, 5124],
    [3809, 5415, 5142]
])

randomData = numpy.random.randint(6, size=3)

print("3 data terpilih untuk dijadikan sampel adalah : ")
for i in randomData:
  print(data[i])


3 data terpilih untuk dijadikan sampel adalah : 
[3572 4129 3251]
[3809 5415 5142]
[3913 5123 4132]


## 2. Random Sampling Pada Set 
Berikut contoh bagaimana cara untuk mengimplementasikan random sampling pada set menggunakan python
### 2.1 Tanpa Redudansi 
Random sampling pada set hanya dapat diimplementasikan tanpa menyertakan redudansi data, hal ini karena set tidak mendukung indexing. Untuk menerapkan random sampling tanpa terjadinya redudansi data, maka kita dapat menggunakan fungsi* random.sample()* <br>
contoh random sampling volume kendaraan pada senin - jumat pada kawasan taman pintar 

In [7]:
import random

data = {4112, 3913, 3572, 4803, 3809}
print("3 data terpilih untuk dijadikan sampel adalah : ", random.sample(data, k=3))



3 data terpilih untuk dijadikan sampel adalah :  [3913, 3809, 4112]


## 3. Random Sampling Pada Dictionary 
Berikut contoh bagaimana cara untuk mengimplementasikan random sampling pada dictionary (objek) menggunakan python
### 3.1 Tanpa Redudansi 
Random sampling pada dictionary hanya dapat diimplementasikan tanpa menyertakan redudansi data, hal ini karena dictionary tidak mendukung indexing. Untuk menerapkan random sampling tanpa terjadinya redudansi data, maka kita dapat menggunakan fungsi *random.sample()* <br>
contoh random sampling volume kendaraan pada senin - jumat pada kawasan taman pintar


In [8]:
import random

data = {
    "senin": 1,
    "selasa": 2,
    "rabu": 3,
    "kamis": 4,
    "jumat": 5
}
print("3 data terpilih untuk dijadikan sampel adalah : ", random.sample(data.items(), k=3))


3 data terpilih untuk dijadikan sampel adalah :  [('selasa', 2), ('rabu', 3), ('jumat', 5)]
